apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      containers:
      - name: backend
        image: ammu172/ecommerce:backend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "mysql-service.ecommerce.svc.cluster.local"
        - name: DB_USER
          value: "admin123"
        - name: DB_PASSWORD
          value: "password123"
        - name: DB_NAME
          value: "ecommerce_db"
        - name: DB_PORT
          value: "3306"
        - name: JWT_SECRET
          value: "my_super_secret_key_2024"
        - name: PORT
          value: "5000"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10

