---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  DB_HOST: "ecommerce.ctuwsqiwsbci.ap-south-1.rds.amazonaws.com"
  DB_USER: "admin123"
  DB_NAME: "ecommerce_db"
  DB_PORT: "3306"
  NODE_ENV: "production"

